// <auto-generated />
using ApiEventosCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApiEventosCore.Migrations
{
    [DbContext(typeof(EventosDataContext))]
    [Migration("20170923183834_ChangeType")]
    partial class ChangeType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiEventosCore.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EVEN_ID");

                    b.Property<bool>("Cancelado")
                        .HasColumnName("EVEN_CANCELADO");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnName("EVEN_DATA_DE_CADASTRO");

                    b.Property<string>("DataFim")
                        .IsRequired()
                        .HasColumnName("EVEN_DATA_FIM");

                    b.Property<string>("DataInicio")
                        .IsRequired()
                        .HasColumnName("EVEN_DATA_INICIO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("EVEN_DESCRICAO")
                        .HasMaxLength(500);

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnName("EVEN_HORA_FIM");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnName("EVEN_HORA_INICIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("EVEN_NOME")
                        .HasMaxLength(60);

                    b.Property<int>("UsuarioId")
                        .HasColumnName("EVEN_USUARIO_ID");

                    b.HasKey("Id");

                    b.ToTable("EVENTO");
                });

            modelBuilder.Entity("ApiEventosCore.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USUA_ID");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("USUA_DATACADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("USUA_EMAIL")
                        .HasMaxLength(60);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("USUA_NOME")
                        .HasMaxLength(60);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("USUA_SENHA")
                        .HasMaxLength(200);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("USUA_USER_NAME")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
